-- ============================================================
-- Delta_Verse: RLS lockdown + wip_waitlist table
-- Run this once in Supabase Dashboard > SQL Editor > New query > Run
-- ============================================================

-- 1) New table backing the WIP "notify me at launch" capture form
create table if not exists public.wip_waitlist (
  id bigint generated by default as identity primary key,
  project_name text not null,
  email text not null,
  created_at timestamptz not null default now()
);

-- 2) Drop every existing policy on these tables first (safe no-op if none exist).
--    This guarantees we start from a clean slate regardless of what's currently
--    granting the anon key unrestricted SELECT access.
do $$
declare
  pol record;
  tbl text;
begin
  foreach tbl in array array['enquiries', 'bookings', 'orders', 'wip_waitlist']
  loop
    for pol in
      select policyname from pg_policies
      where schemaname = 'public' and tablename = tbl
    loop
      execute format('drop policy if exists %I on public.%I', pol.policyname, tbl);
    end loop;
  end loop;
end $$;

-- 3) Enable RLS everywhere
alter table public.enquiries enable row level security;
alter table public.bookings enable row level security;
alter table public.orders enable row level security;
alter table public.wip_waitlist enable row level security;

-- 4) enquiries: public contact form can INSERT; only the logged-in dashboard
--    can SELECT / UPDATE (status changes) / DELETE (archive)
create policy "enquiries_insert_public" on public.enquiries
  for insert to anon, authenticated with check (true);
create policy "enquiries_select_auth" on public.enquiries
  for select to authenticated using (true);
create policy "enquiries_update_auth" on public.enquiries
  for update to authenticated using (true) with check (true);
create policy "enquiries_delete_auth" on public.enquiries
  for delete to authenticated using (true);

-- 5) bookings: no public write path exists today, so dashboard-only for everything
create policy "bookings_select_auth" on public.bookings
  for select to authenticated using (true);
create policy "bookings_insert_auth" on public.bookings
  for insert to authenticated with check (true);
create policy "bookings_update_auth" on public.bookings
  for update to authenticated using (true) with check (true);
create policy "bookings_delete_auth" on public.bookings
  for delete to authenticated using (true);

-- 6) orders: only ever created from the logged-in "Add Order" modal
create policy "orders_select_auth" on public.orders
  for select to authenticated using (true);
create policy "orders_insert_auth" on public.orders
  for insert to authenticated with check (true);
create policy "orders_update_auth" on public.orders
  for update to authenticated using (true) with check (true);
create policy "orders_delete_auth" on public.orders
  for delete to authenticated using (true);

-- 7) wip_waitlist: public "notify me" form can INSERT; only dashboard can read/delete
create policy "waitlist_insert_public" on public.wip_waitlist
  for insert to anon, authenticated with check (true);
create policy "waitlist_select_auth" on public.wip_waitlist
  for select to authenticated using (true);
  
create policy "waitlist_delete_auth" on public.wip_waitlist
  for delete to authenticated using (true);
