-- ============================================================
-- Delta_Verse: Testimonials table + RLS
-- Run this once in Supabase Dashboard > SQL Editor > New query > Run
-- (Additive to supabase_rls.sql — safe to run independently)
-- ============================================================

-- 1) Testimonials table
create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  client_name text not null,
  client_title text,
  project_name text,
  quote text not null,
  rating smallint check (rating between 1 and 5),
  is_published boolean not null default false,
  created_at timestamptz not null default now()
);

-- 2) Drop any existing policies on this table first (safe no-op if none exist)
do $$
declare
  pol record;
begin
  for pol in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = 'testimonials'
  loop
    execute format('drop policy if exists %I on public.testimonials', pol.policyname);
  end loop;
end $$;

alter table public.testimonials enable row level security;

-- 3) Public site can read only published testimonials
create policy "testimonials_select_published_public" on public.testimonials
  for select to anon
  using (is_published = true);

-- 4) Dashboard (authenticated) can read everything, including unpublished drafts
create policy "testimonials_select_all_auth" on public.testimonials
  for select to authenticated
  using (true);

-- 5) Only the dashboard can add/edit/delete testimonials
create policy "testimonials_insert_auth" on public.testimonials
  for insert to authenticated with check (true);
create policy "testimonials_update_auth" on public.testimonials
  for update to authenticated using (true) with check (true);
create policy "testimonials_delete_auth" on public.testimonials
  for delete to authenticated using (true);
